### ISSUE TITLE
L'extension ne fonctionne plus

### ISSUE THREAD

**Issue by Bouh** [antoineraulin/deepl-chrome-extension#1]
L’extension ne fonctionne plus :/

**Comment by antoineraulin** [comment]
Effectivement, il faudrait que je regarde. L'extension n'avait jamais réellement fonctionnée comme je le souhaitais, elle est un peu tombée à l'abandon.
De plus, à moins d'utiliser une version bêta de chrome, on ne peut plus installer d'extension sans passer par le web store. J'y jetterai un œil quand j'aurai le temps malheureusement. 
Merci en tout cas d'avoir remonté ce pb

**Comment by Bouh** [comment]
Tentez une approche avec les script greasemonkey/tampermonkey.
Ça contourne les restrictions de Chrome, et des web store en général.

**Comment by antoineraulin** [comment]
Merci de continuer à vous intéresser à mon projet ! Je ne vous cache pas que j'avais oublié cette histoire. Je vais me remettre dessus, votre idée me semble en effet la plus judicieuse.

**Comment by Bouh** [comment]
Ca semble plus tricky maintenant, les appels à l'api semblent être un peut différent, j'ai vu pas mal de repo qui cherche à faire la même chose en vain. 
L'erreur 403 est présente souvent avec les appel api des différentes extensions, faudra peut être faire un appel à une iframe pour transmettre le texte, puis récupéré le contenu traduit de l'iframe.
J'ai survolé tout ça jetez y un oeil quand même vous verrez peut être une solution de contournement.

Je me suis fait blacklisté mon ip sur leur services haha, Ils détectent quelques choses je ne sais pas comment.

Le projet à l'air cool, votre code d'extension aussi. Tentons de faire fonctionné tout ça!
`https://test.d eepl.com/js/translator/Translator_main.js`

https://pastebin.com/raw/exh48smJ
& 
https://pastebin.com/raw/gRehpkTp

**Comment by antoineraulin** [comment]
Effectivement, je me suis aussi déjà fait blacklist, et pourtant c'était dans un autre projet pour lequel j'ai utilisé puppeteer pour échapper aux restrictions de l'API. Sûrement une sécu sur le nombre de requêtes sur une période.

Ils ont récemment mis en place une application pour Windows pour faire des traductions, je ne sais pas si le code source est disponible. Si oui, cela pourrait nous aider.

L'idée d'utiliser un iframe pourrait nous aider a éviter ces problèmes avec deepl, mais je pense que cela aura un effet fortement négatif sur les performances de l'extension. Mon code original n'était déjà pas très rapide. Sans compter qu'il n'est pas facile de maintenir une syntaxe et une phrase compréhensive quand on doit découper les phrases à cause des balises HTML.

**Comment by Bouh** [comment]
Regarde les deux liens que j'ai mis ils sont issu du log de leur application.
Il y a du C# dans leur projet je crois. Mais je pense qu'il appel leur API avec une clé qu'on pourrait essayé de retrouvé dans leur app avec de la rétro-ingénierie.
